### PR TITLE
Fix GroupMap if store or group have no location

### LINKED ISSUE #602: Map shows  Darmstadt when no markers
In group 20 there is no store location specified. The map thus doesn't zoom into any location, even though a group location is added.

It would be better if the map zoomed into the group location, if no store location data was provided.
No marker should be displayed at the group location.

### PR DESCRIPTION
**Pull request by tiltec**
- if on group page and no markers are available and group location is not set, show button "set group location"
nogrouplocation
- if only group location is available, show low zoom on group location
grouplocation
- if in store mode and store location is not available, show button "set store location"
nostorelocation

Closes #602

### CODE REVIEW

File: src/pages/Map.vue [hunk 1]
```diff
@@ -15,8 +15,9 @@ export default {
   components: { GroupMap },
   computed: {
     ...mapGetters({
-      stores: 'stores/byActiveGroup',
-      users: 'users/all',
+      stores: 'stores/withLocation',
```
Comment (nicksellen) [inline src/pages/Map.vue]: Is this really meaning `byActiveGroupWithLocation`?

from reading just the name it looks like it could overfetch the stores, and show ones for other groups.

File: src/store/modules/stores.js [hunk 2]
```diff
@@ -39,7 +39,7 @@ export const getters = {
   all: state => state.idList.map(i => state.entries[i]).sort(sortByName),
   byActiveGroup: (state, getters, rootState, rootGetters) => getters.all.filter(e => e.group === rootGetters['groups/activeGroupId']),
   get: state => (id) => state.entries[id],
-  withLocation: (state, getters) => getters.all.filter(e => e.longitude && e.latitude),
+  withLocation: (state, getters) => getters.byActiveGroup.filter(e => e.longitude && e.latitude),
```
Comment (nicksellen) [inline src/store/modules/stores.js]: Hmm, as comment above, I find this unclear that it filters by active group without saying so in the name.

I would be happy without the `withLocation` getters, and rely on the map to filter those out (which it has to do anyway...)

File: src/locales/locale-en.json [hunk 3]
```diff
@@ -298,5 +298,7 @@
   "already taken": "Already taken",
   "Enter a valid timezone": "Enter a valid timezone",
   "write a message": "Write a message...",
-  "write the first message": "Write the first message..."
+  "write the first message": "Write the first message...",
```
Comment (nicksellen) [inline src/locales/locale-en.json]: I think we need to rationalize this locale approach, seems to be append-only lately...

File: src/components/Map/StandardMap.vue [hunk 4]
```diff
@@ -86,8 +87,25 @@ export default {
...
-      else {
-        return L.latLngBounds([{ lat: '49.8990022441358', lng: '8.66415739059448' }])
+    },
+    center () {
+      if (!this.bounds) {
+        if (this.defaultCenter) {
+          return [this.defaultCenter.latitude, this.defaultCenter.longitude]
+        }
+        else {
+          return ['49.8990022441358', '8.66415739059448']
```
Comment (nicksellen) [inline src/components/Map/StandardMap.vue]: Should be most amusing place possible...

File: src/store/modules/stores.js (hunk 2 above)
Comment (tiltec) [reply src/store/modules/stores.js]: Yep, will remove the withLocation getters and handle it in the groupMap component

File: src/locales/locale-en.json (hunk 3 above)
Comment (tiltec) [reply src/locales/locale-en.json]: For sure, we also need to add a lot of untranslated stuff into locale-en...

File: src/components/Map/StandardMap.vue (hunk 4 above)
Comment (tiltec) [reply src/components/Map/StandardMap.vue]: it's still Darmstadt 🍂
